### ISSUE TITLE
Forseen denoised observation

### ISSUE THREAD

**Issue by Trainingzy** [KAIST-Geometric-AI-Group/SyncDiffusion#1]
Hi, thanks for your great work.

I have a question regarding Eq. 14. Is $\phi(x_t,t)$ equivalent to conducting one step denoising for $x_t$? If so, does this only make sense in the early denoising stage? Have you compared Eq. 13 and Eq. 14 qualitatively or quantitatively?

**Comment by phillipinseoul** [comment]
Sorry for the late response :)

(1) $\phi(x, t)$ is the denoised prediction of $x_0$ from $x_t$ as defined in Eq. 10. 
(2) In Sec. 6.5 and Tab. 2 of our Supplementary, we compare the results of using Eq. 13 and Eq. 14.

Thanks for having interest in our work.
