### ISSUE TITLE
What LICENSE Does This Model Have?

### ISSUE THREAD

**Issue by zsxkib** [KAIST-Geometric-AI-Group/SyncDiffusion#4]
Hello SyncDiffusion Team,

Firstly, I want to extend my compliments on the exceptional work you've done with the SyncDiffusion model. It's so impressive.

I'm part of the team at [Replicate](https://replicate.com/), where we're enthusiastic about making pioneering models like yours accessible to the wider open-source community. We are considering implementing your model on our platform, which caters to both research-focused and commercial applications.

To proceed, we would greatly appreciate it if you could clarify the licensing terms for the SyncDiffusion model. Understanding the license will help us ensure that we align with your guidelines and intentions for the model's use.

Thank you for your time and contribution to the field. We're looking forward to potentially collaborating and bringing your model to a broader audience.

Best regards,
Sakib

**Comment by phillipinseoul** [comment]
Hi,
Thank you for considering integrating our work into your platform!
I added the MIT License to our repository. Hope it helps :)

**Comment by zsxkib** [comment]
Thank you so much :)
